!!com.github.adminfaces.addon.scaffold.model.GlobalConfig
toOneComponentType: AUTOCOMPLETE
toManyComponentType: CHECKBOXMENU
dateComponentType: CALENDAR
datatableEditable: false
inputSize: 100
menuIcon: "fa fa-circle-o"